### PR TITLE
option to set initial volume level

### PR DESCRIPTION
**Pull request by borine**
A simple change, if the concept is acceptable then hopefully the implementation can be reviewed in time for the coming release.

Addresses a comment that has been made a number of times in issues, most recently here https://github.com/Arkq/bluez-alsa/issues/453#issuecomment-851735570

### CODE REVIEW

**Comment by Arkq** [comment]
I think that the idea is OK. Once I though about persistent volume control (like in ALSA), but I come to a conclusion that it should be done in BlueZ, not BlueALSA. BlueZ already has a cache for connected/remembered devices. For instance it remembers lastly used codec for A2DP (I've not checked whether it will persist BlueZ daemon restart, though). So it would be reasonable to keep there a volume level, if sink device does not report/set initial volume.

One thing that I would change (cosmetic change): rename `a2dp.initial_volume` -> `a2dp.volume_init_level` and place it right after `a2dp.volume`. I often use "namespaced" variables, so they are sorted in the auto-completion list in most IDEs/editors.

As for command like option name I also thought about something along `--a2dp-volume-initial-level`, but this will result in too long option.. :/ So, I think that `--a2dp-initial-volume` is OK.

I'm not sure, whether it is right to remove the "Skip volume level initialization in case of A2DP Source profile and software volume control" `if`. Because it's there for a reason. When software volume is enabled, BlueALSA scales volume internally. So, if you set initial "hardware" volume you will have double volume scaling - by BlueALSA and later by sink BT device. Let say that you will set initial volume to 20%, this will result in 20% attenuation by BlueALSA, and later 20% (of this already attenuated sound) by sink device. As a result you will hear nothing.

**Comment by borine** [comment]
> remove the "Skip volume level initialization in case of A2DP Source profile and software volume control" if

OK - that was completely wrong. I've force pushed a new version that hopefully get the initialization right. This sets initial softvol level for both source and sink - I'm not sure if that is right, and I have no way of testing what happens when bluealsa is the sink. Is this correct, or should this option  only be applied where bluealsa is the source?

**Comment by Arkq** [comment]
>  I've force pushed a new version that hopefully get the initialization right. 

Yes, right now the initialization is done in a right way.

I've tested it and I've got a second thought. I think that this feature should be more generic (I'm not sure how much, though). Right now it's only for software volume control, only for A2DP. I think that it should be for SCO as well and not only for software volume. The initialization part is OK, but please remove the `if (!config.a2dp.volume)` - this will resolve the "not only for software volume".

**Rationale:**
Without this patch, the initial value is 0 dB for soft and non-soft volume. With this patch it should be a value specified by a user, so later it could be overwritten by BT device if BT device supports volume notification (either A2DP or HFP). Otherwise (or in case of soft volume), it will stay as a default until user will not change it via BlueALSA D-Bus API (e.g. `amixer -D bluealsa`).

Since I would like it to be also for SCO, now we have to face two things. Firstly, SCO and A2DP uses two different ranges for volume (0-127 vs 0-15). Secondly, SCO (HFP) has a backchannel stream (microphone) with a separate volume control. So, the command line option(s) should allow to set volume for speaker and for mic. With A2DP it is a little bit simpler at first glance (but in reality it's more complicated). A2DP specification does not mention anything about volume control for backchannel, because backchannel is not part of standard spec. However, from the user point of view it would be nice to be able to set the volume for microphone as well (e.g. in case of FastStream codec), even though there is not dedicated volume control in AVRCP spec (maybe it will be in the future). So, the problem is, how to design command line interface for this. As a result we've got a lot of configurations which does not necessarily fit into the command line. So my proposition is to use a single option which will set initial volume (loudness) for both A2DP and SCO for main stream and backchannel, e.g. `--init-volume=X` where X is in range 0-100. What do you think?

**Comment by borine** [comment]
> What do you think?

I'm thinking there's more to this than I first imagined. So I recommend that the 3.1.0 release is done first, and then the ideas in here can be developed with time to experiment with different options.

Having persistent settings per device sounds like an excellent idea. I can't find the Bluez API for this though.

**Comment by graham8** [comment]
I don't think I've come across a BT device that doesn't have automatic volume control on the mic.  As such, I doubt mic volume would get much use.

But my experience is very limited :)

**Comment by Arkq** [comment]
> Having persistent settings per device sounds like an excellent idea. I can't find the Bluez API for this though.

I doubt that there is such public D-Bus API. Device cache (mainly SEPs) is an internal BlueZ thingy.

> As such, I doubt mic volume would get much use.

It might be of no use for many, but might irritate few. I think that for the correctness sake, setting initial volume (and volume scaling) should be for speaker and microphone (in general for main stream and backchannel stream). It's not a technical challenge (this PR already does that) but rather a presentation layer challenge - how to expose these settings to end-user.

My further idea was to add "special" values for `--init-volume` option. In general it would accept integer value, but one could specify e.g. `--init-volume=a2dp:80 --init-volume=sco:50` which will set A2DP initial volume to 80% and SCO initial volume to 50%. Further distinction might be a2dp sink, a2dp source, a2dp sink main channel, a2dp sink backchannel, sco audio gateway speaker, sco audio gateway mic, etc. But the number of possibilities very easy gets out of hands, so maybe that's not a good idea after all :D

**Review by Arkq — APPROVED** [review]

**Comment by Arkq** [comment]
Feature applied. I've changed the option name to `--initial-volume`, though. Since there is no `a2dp` prefix, the verbose option name is not too long, so I think it's better to keep it that way.

**Pull request closed without merging**
