### PR TITLE
Added basic Yocto/OE receipe

### PR DESCRIPTION
**Pull request by dagf2101**
Here is the receipe I made for yocto/open-embedded, It may not be super complete but it worked for me and can be a pretty good stating point for others.

Cheers.

### CODE REVIEW

**Comment by Arkq** [comment]
Hi, I'm glad you've made this bitbake recipe. However, I'm not sure if this repository is a right place for it. IMHO is should be included in the Yocto project (or some other project which gathers bb files). I'm not a fan of including distribution related files into the application repository. There is a multitude of distributions, so it would be very inconvenient to keep configuration files for all of them in this repo.

Unfortunately, I don't know where to redirect you to. I've never made any "pull requests" for Yocto project (if it is possible)... I myself have got a [repository](https://github.com/Arkq/kindle-env) for OpenEmbedded, however it is Kindle related and Kindle does not have Bluetooth (?), so this recipe does not fit in there either.

**Comment by dagf2101** [comment]
Your right this is not the right place, we should place it near the Alsa recipes. One thing for sure is that I will not maintain it so for now you could simply fork this repo: https://github.com/openembedded/meta-openembedded
Put it right near alsaequal in recipes-multimedia and point on it in your readme file.

I admit I simply put the recipe there If you wanted to take it.

Have u had time to look at my issue with Alsaequal ?

Cheers.

**Comment by Arkq** [comment]
I will keep this PR open, so maybe someone will find it useful :)

**Comment by infirit** [comment]
You could enable the wiki and keep it there 😄

**Comment by Arkq** [comment]
Files moved to https://github.com/Arkq/bluez-alsa/wiki/Yocto-OE-recipe
Wiki is enabled for everyone, so fill free to contribute.

@infirit thx for this hint :)

**Pull request closed without merging**
