### PR TITLE
playback start_threshold polling solution

### PR DESCRIPTION
**Pull request by borine**
Here's a quick stab at a polling implementation of the start_threshold issue discussed in #247 
It works OK with my test files with mpg123 and sox play

### CODE REVIEW

**Comment by Arkq** [comment]
Hi @borine, sorry for a delay with a response, but I've got busy.

I've just tried to test this PR, however, in order to test it properly I'd like to see the incorrect behavior of mpg123. Unfortunately, my mpg123 does not hang when playing directly with bluealsa. My setup is as follows:

BlueALSA server launched with forced 44.1kHz sampling:
```sh
$ bluealsa -p a2dp-source --a2dp-force-audio-cd
```

```sh
$ cat .asoundrc
pcm.jabra-raw {
	type bluealsa
	device "1C:48:F9:9D:81:5C"
	profile "a2dp"
}
```
And I run mpg123 as follow:
```
$ mpg123 -a jabra-raw ~/RockySoundtrack.mp3
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.10; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes
136666.719752428: src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Setting constraints
136666.719815948: src/asound/bluealsa-pcm.c:309: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Closing
136666.722066195: src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Setting constraints
136666.722288746: src/asound/bluealsa-pcm.c:309: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Closing

Directory: /home/arkq/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: RockySoundtrack-cWQluSY36FQ.mp3 ...
136666.724831896: src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Setting constraints
136666.724912910: src/asound/bluealsa-pcm.c:319: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Initializing HW
136666.979996912: src/asound/bluealsa-pcm.c:346: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: FIFO buffer size: 4096
136666.980021744: src/asound/bluealsa-pcm.c:352: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Selected HW buffer: 3 periods x 11760 bytes == 35280 bytes
136666.980040023: src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Initializing SW
136666.980065413: src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Prepared
136666.980079749: src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Initializing SW
136666.980097761: src/asound/bluealsa-pcm.c:280: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Stopping
136666.980177144: src/asound/bluealsa-pcm.c:359: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Freeing HW
136666.980196184: src/asound/bluealsa-pcm.c:309: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Closing

MPEG 1.0 L III vbr 44100 j-s

136666.983176960: src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Setting constraints
136666.983256486: src/asound/bluealsa-pcm.c:319: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Initializing HW
136667.172746725: src/asound/bluealsa-pcm.c:346: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: FIFO buffer size: 4096
136667.172770718: src/asound/bluealsa-pcm.c:352: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Selected HW buffer: 3 periods x 11760 bytes == 35280 bytes
136667.172788332: src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Initializing SW
136667.172814773: src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Prepared
136667.172828409: src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Initializing SW
136667.172851907: src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Starting
136667.175050317: src/asound/bluealsa-pcm.c:134: /org/bluealsa/hci0/dev_1C_48_F9_9D_81_5C/a2dp: Starting IO loop: 8
```

I'm using current master of bluez-alsa and the mpg123 compiled with alsa and sdl support (ebuild from Gentoo). And it seems, that everything works as expected.
Which Linux distro you are using? And which version of mpg123? And where you are testing this, PC or e.g. RPi?

**Comment by borine** [comment]
I'm testing using ubuntu bionic on an intel laptop. mpg123 is from the ubuntu repository:
```
$ mpg123 --version
mpg123 1.25.10
```
Here's the first 100 lines of mpg123 debug output:
```
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.10; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes
../../../src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Setting constraints
../../../src/asound/bluealsa-pcm.c:309: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Closing
../../../src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Setting constraints
../../../src/asound/bluealsa-pcm.c:309: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Closing

Directory: Fleetwood Mac/Heroes Are Hard To Find/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: 01 - Heroes Are Hard to Find.mp3 ...
../../../src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Setting constraints
../../../src/asound/bluealsa-pcm.c:319: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Initializing HW
../../../src/asound/bluealsa-pcm.c:346: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: FIFO buffer size: 4096
../../../src/asound/bluealsa-pcm.c:352: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Selected HW buffer: 3 periods x 11760 bytes == 35280 bytes
../../../src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Initializing SW
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Initializing SW
../../../src/asound/bluealsa-pcm.c:280: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Stopping
../../../src/asound/bluealsa-pcm.c:359: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Freeing HW
../../../src/asound/bluealsa-pcm.c:309: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Closing

MPEG 1.0 L III vbr 48000 j-s

Title:   Heroes Are Hard to Find         Artist: Fleetwood Mac                 
Album:   Heroes Are Hard To Find
../../../src/asound/bluealsa-pcm.c:589: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Setting constraints
../../../src/asound/bluealsa-pcm.c:319: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Initializing HW
../../../src/asound/bluealsa-pcm.c:346: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: FIFO buffer size: 4096
../../../src/asound/bluealsa-pcm.c:352: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Selected HW buffer: 3 periods x 11760 bytes == 35280 bytes
../../../src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Initializing SW
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:367: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Initializing SW
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:134: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting IO loop: 8
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
../../../src/asound/bluealsa-pcm.c:148: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread resumed: 3
../../../src/asound/bluealsa-pcm.c:145: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: IO thread paused: 4
../../../src/asound/bluealsa-pcm.c:389: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Prepared
../../../src/asound/bluealsa-pcm.c:240: /org/bluealsa/hci0/dev_C4_67_B5_37_26_FC/a2dp: Starting
```
The music does play, and cpu load is low, but that paused/prepared/starting/resumed cycle continues roughly 500 times per second.

Is it possible that the Gentoo mpg123 build is patched to remove the start_threshold setting?

**Comment by borine** [comment]
I've repeated the test using a rpi 3B+ and the result is the same as the laptop - the terminal is spammed with pause/prepare/start/resume messages.
A quick look at the Gentoo sources suggests there is no patch.
Hmm - leave this alone for a while, I'll have to see if something else is wrong with my setup. Maybe I'll try building mpg123 myself to see what happens.

**Comment by borine** [comment]
OK, so I've build mpg123 v 1.25.10 from sources, and I still see the above debug messages spamming the terminal. However, when I edit the mpg123 sources:
```
src/libout123/modules/alsa.c:139
<	if (snd_pcm_sw_params_set_start_threshold(pcm, sw, 1) < 0) {
>	if (snd_pcm_sw_params_set_start_threshold(pcm, sw, period_size) < 0) {
```
Then the spam goes away and my debug messages are the same as yours.
So I'm convinced my original analysis was correct, but I'm at a loss to explain why you are not getting the same results.

**Comment by Arkq** [comment]
> So I'm convinced my original analysis was correct, but I'm at a loss to explain why you are not getting the same results.

Yes, that's strange. I'll try to compile it by myself as well to see whether it will break. Anyway, your patch seems legit :)

**Comment by Arkq** [comment]
I've compiled mpg123 manually and to my surprise it works too (`./configure --with-default-audio=alsa`). So, I though that the only reasonable explanation is alsa-lib difference... I'm using alsa-lib-1.1.8, maybe it has a fix for premature start... So, I've compiled alsa-lib-1.1.7... which works too :D 

Buuut... after few tries, I was able to see terminal flood! So, indeed there is a bug, however, it's really hard to reproduce (for me). The mpg123 and alsa-lib version does not matter, though.

**Comment by borine** [comment]
I think the behaviour depends on how fast the application thread can write to the buffer while the io thread is starting up. So it may depend on data file contents as well as thread scheduling. 
This fix is not perfect - for example if the buffer is just one frame short of the period then the io thread will wake (e,g.) 48000 times per second, which is beginning to look like a busy loop to me.
If new issues are logged against mpg123 then it may be necessary to revisit this.

**Pull request closed without merging**
