### PR TITLE
Build and install shared code as a shared library

### PR DESCRIPTION
**Pull request by wberrier**
Thoughts?  Changes?

### CODE REVIEW

**Comment by Arkq** [comment]
Hi, thx for the PR. I will review this during the weekend. There are
few things I'd like to address, however right now I've got no access to
my github account :D

**Comment by snehaltan** [comment]
Any plans to merge this PR? It is quite helpful to me, I could just checrrypick this change if this is not planned for merge.

**Comment by Arkq** [comment]
@snehaltan Yes, I've got this PR at the back of my mind all the time. Eventually it will be merged (I'm not sure if in the current form, though). However, merging this will require library maintenance (correct versioning), which will add a little bit of overhead to the project. I'm waiting until this "library" code will be more of less mature. I'm not able to tell any exact date, however expect something between half to one year from now.

**Comment by snehaltan** [comment]
@Arkq . Thanks for confirming. I have cherry picked the change for now.

**Comment by Arkq** [comment]
Right now shared code related to ctl interface is gone. One should use D-Bus interface described here: https://github.com/Arkq/bluez-alsa/blob/master/doc/bluealsa-api.txt

**Pull request closed without merging**
