### PR TITLE
Pcm list

### PR DESCRIPTION
**Pull request by Arkq**
@borine what do you think about this? I've experimented with printing bluealsa pcm dbus device path, but it seems to be too much bloat imho. I've seen your script for pulseaudio and I thought that such listing might be useful for you, but I'm not sure what kind of information shall be in it.

### CODE REVIEW

**Comment by graham8** [comment]
This looks promising.  We are looking for a way to get Kodi to enumerate available BT devices along with ALSA devices. If this does the heavy lifting that's great!

**Comment by Arkq** [comment]
@graham8 what kind of information you need in such listing?

**Comment by Arkq** [comment]
Currently the output looks like this:
```
arkq ~ $ bluealsa-aplay -l
**** List of PLAYBACK Bluetooth Devices ****
hci0: F8:87:F1:B8:30:85 [iPhone], trusted phone
**** List of CAPTURE Bluetooth Devices ****
hci0: F8:87:F1:B8:30:85 [iPhone], trusted phone
arkq ~ $
arkq ~ $ bluealsa-aplay -L
**** List of PLAYBACK Bluetooth Devices ****
  SCO (N/A): S16_LE 1 channel 0 Hz
**** List of CAPTURE Bluetooth Devices ****
  SCO (N/A): S16_LE 1 channel 0 Hz
  A2DP (AAC): S16_LE 2 channels 44100 Hz
arkq ~ $
arkq ~ $ bluealsa-aplay -l -L
**** List of PLAYBACK Bluetooth Devices ****
hci0: F8:87:F1:B8:30:85 [iPhone], trusted phone
  SCO (mSBC): S16_LE 1 channel 16000 Hz
hci0: 10:B1:F8:E6:10:D4 [HUAWEI], trusted phone
  SCO (CVSD): S16_LE 1 channel 8000 Hz
**** List of CAPTURE Bluetooth Devices ****
hci0: F8:87:F1:B8:30:85 [iPhone], trusted phone
  SCO (mSBC): S16_LE 1 channel 16000 Hz
  A2DP (AAC): S16_LE 2 channels 44100 Hz
hci0: 10:B1:F8:E6:10:D4 [HUAWEI], trusted phone
  A2DP (SBC): S16_LE 2 channels 44100 Hz
  SCO (CVSD): S16_LE 1 channel 8000 Hz
```

**Comment by graham8** [comment]
All we would need is the MAC for playback devices and a corresponding human-readable name (BT Name) for display in the audio sink list.

**Comment by paul-1** [comment]
I use python to grab that info from dbus, but sometimes it's nice to check things the easy way.  Is codec selection possible/working?  

One comment, I've typically seen on alsa programs -l show the short list, and -L show the long list.  I've not seen them used together.

**Comment by Arkq** [comment]
> One comment, I've typically seen on alsa programs -l show the short list, and -L show the long list. I've not seen them used together.

I thought about the same modification. Indeed, it will be more convenient to show verbose listing with `-L` alone. I'll change that in the final version (`-l -L` -> `-L`). Thanks for the feedback!

**Comment by borine** [comment]
wow, that was quick!
Some thoughts on the output format:

`aplay -L`  gives a listing from which it is easy to parse the device string required for the -D param to alsa applications. So perhaps `bluealsa-aplay -L` should do similarly, except that of course aplay lists playback pcms and arecord is used to list capture pcms.

It would be nice if we could get an output like 
```
borine ~ $ bluealsa-aplay -L
bluealsa:DEV=F8:87:F1:B8:30:85,PROFILE=sco
      iPhone, trusted phone (hci0) Playback
      SCO (mSBC): S16_LE 1 channel 16000 Hz
bluealsa:DEV=10:B1:F8:E6:10:D4,PROFILE=sco
      HUAWEI, trusted phone (hci0) Playback
      SCO (CVSD): S16_LE 1 channel 8000 Hz
bluealsa:DEV=F8:87:F1:B8:30:85,PROFILE=sco
      iPhone, trusted phone (hci0) Capture
      SCO (mSBC): S16_LE 1 channel 16000 Hz
bluealsa:DEV=F8:87:F1:B8:30:85,PROFILE=a2dp
      iPhone, trusted phone (hci0) Capture
      A2DP (AAC): S16_LE 2 channels 44100 Hz
bluealsa:DEV=10:B1:F8:E6:10:D4,PROFILE=a2dp
      HUAWEI, trusted phone (hci0) Capture
      A2DP (SBC): S16_LE 2 channels 44100 Hz
bluealsa:DEV=10:B1:F8:E6:10:D4,PROFILE=sco
      HUAWEI, trusted phone (hci0) Capture
      SCO (CVSD): S16_LE 1 channel 8000 Hz
```
aplay -l lists hardware cards, so there is no direct equivalent for bluealsa. Perhaps your example `bluealsa-aplay -l -L` output could be instead provided by `bluealsa-aplay -l`. Not sure really, I guess go with whatever feedback you get here. When I suggested this, I was imagining output that could be parsed by current scripts that invoke aplay -l, aplay -L, arecord -l, and arecord -L. However I must admit I hadn't (and still haven't) really thought it through in any detail

As for the "bluepulse" script, that needs to parse dbus signals to detect device connection and disconnection events, so I don't think I would use this anyway.

**Comment by Arkq** [comment]
> wow, that was quick!

Yes, I prefer rapid development :D But seriously, this is rather a simple feature, and the final output format can be discussed in more details after merging architectural changes - master branch is for development after all.

> aplay -L gives a listing from which it is easy to parse the device string required for the -D param to alsa applications. So perhaps bluealsa-aplay -L should do similarly, except that of course aplay lists playback pcms and arecord is used to list capture pcms.

Hmm... maybe you are right about printing output in a compatible way with aplay's `-D`. It will be much easier to use it then. I did not thought about that.... one again great idea :)

@borine what would you say about becoming a collaborator for this repository? You are the most active person in the issues section and wiki anyway. After becoming a collaborator it will be possible to e.g. assign you as a reviewer for PRs, so before merging new features/changes it will be possible to have an open discussion beforehand. What would you say?

**Comment by borine** [comment]
@Arkq I am happy to discuss any changes, but have limited time available and would not want to delay development in anyway. So, as long as responses from me are optional and never required to keep development moving, then I have no objection in principle to becoming a collaborator. I would not want to make any commits to the bluealsa codebase though.

**Comment by Arkq** [comment]
@borine, that's great! Do not be worried about development slow down, the pace is not so high anyway, e.g. comparing with commercial products. And about making commits, also don't worry, I will still maintain this project, so commits are on me, all I ask is some code review from time to time :)

PS. I've pushed changes suggested by you to `pcm-list` branch (with minor changes). Also, I've changed option names for `bluealsa-aply` to reflect `aplay`/`arecord` options, so there will be compatibility break (next bluez-alsa release version will be 3.0 anyway due to required D-Bus changes).

**Comment by graham8** [comment]
oooh. What's happening with D-Bus?

**Comment by Arkq** [comment]
@graham8 commits 6ce4c8e, b3dbf01 and 3caef65 introduced incompatible BlueALSA D-Bus API changes (required for bluez-alsa architectural changes). So, if someone was using BlueALSA D-Bus API, there might be required some adaptation after version 3.0 will be released (or when using bluez-alsa master branch). Hopefully, these changes will make BlueALSA D-Bus API usage more simple.

**Comment by paul-1** [comment]
Good, I’ve already made the needed changes then

**Pull request merged**
